[pytest]
markers =
    booking: booking test
    cancel: cancel test
    login: login test
    pnr: pnr test
    chartvacancy: chart vacancy test
    addtocart: add to cart test
    travel: travel test
    mytrips: my trips test
    plantrip: plan trip test
    search: search test
    login_irctc: IRCTC login and search trains test
